language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
env:
  - MAKEFLAGS="-j3"
before_install:
  - if [ `uname` = "Linux" ]; then
      sudo apt-get install gfortran -y;
    elif [ `uname` = "Darwin" ]; then
      brew install pkg-config;
    fi
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("OptimizationServices"); Pkg.test("OptimizationServices"; coverage=true)'
